server:
  port: 8085

spring:
  application:
    name: authentication-api

  datasource:
    url: ${capstone_db}
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://server-api:8761/eureka/